DROP TABLE ORGANIZATION;
DROP TABLE EVENT_INFO;
DROP TABLE PARTICIPANT;

CREATE TABLE ORGANIZATION
(   O_ID          INT             PRIMARY KEY   AUTO_INCREMENT,
    NAME          VARCHAR(255)    NOT NULL,
    PASSWORD      VARCHAR(255)    NOT NULL,
    ADDRESS       VARCHAR(255),
    WEBSITE       VARCHAR(255),
    EMAIL         VARCHAR(255)    NOT NULL);

CREATE TABLE EVENT_INFO
(   E_ID          INT PRIMARY KEY AUTO_INCREMENT,
    O_ID          INT NOT NULL,
    TITLE         VARCHAR(255)    NOT NULL,
    SUMMARY       VARCHAR(1024)   NOT NULL,
    LOCATION      VARCHAR(255)    NOT NULL,
    E_TIME        TIMESTAMP       NOT NULL,
    C_TIME        TIMESTAMP       NOT NULL      DEFAULT CURRENT_TIMESTAMP,
    PHONENUMBER   INT(10)         NOT NULL,
    TOTAL_SPOT    INT,
    CURRENT_SPOT  INT             DEFAULT 0,
    FOREIGN KEY (O_ID) REFERENCES ORGANIZATION(O_ID)
);

CREATE TABLE PARTICIPANT
(   EMAIL         VARCHAR(255)    PRIMARY KEY,
    PASSWORD      VARCHAR(255)    NOT NULL,
    NAME          VARCHAR(255)    NOT NULL,
    ADDRESS       VARCHAR(255)    NOT NULL,
    PHONENUMBER   VARCHAR(255)    NOT NULL,
    C_TIME        TIMESTAMP       NOT NULL      DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE EVENT_PARTICIPANT
(   E_ID          INT             PRIMARY KEY,
    EMAIL         VARCHAR(255)    PRIMARY KEY,
    NPARTICIPANTS INT             NOT NULL      DEFAULT 1,
    FOREIGN KEY (E_ID) REFERENCES EVENT_INFO(E_ID),
    FOREIGN KEY (EMAIL) REFERENCES PARTICIPANT(EMAIL)
);
